[package]
name = "kb_host"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8"
dirs = "4.0"
eframe = "0.19"
egui = "0.19"
hidapi = "2.0"
palette = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
